---
title: "NBS_EU"
output: html_document
date: "2023-06-11"
---

## NbS approach accounting and selecting

Take **'Gothenburg'** as an example -

```{r}
library(raster)
library(rgdal)
library(maptools)
library(raster)
options(stringsAsFactors = FALSE)
library(mapproj)
library(ggplot2)
```

```{r}
#access data
pop <- raster("D:/EU/Cities/Collection/POP_GOT.tif")
lu <- raster("D:/EU/Cities/Collection/LU_GOT.tif")
ind <- raster("D:/EU/comparison/new/Results_ind_GOT_new.tif")
trans <- raster("D:/EU/comparison/new/Results_Trans_GOT_new.tif")
res <- raster("D:/EU/comparison/new/Results_res_GOT_new.tif")


crs(lu) <- crs(ind)
crs(trans) <- crs(ind)
crs(pop) <- crs(ind)
extent(lu) <- extent(ind)
extent(trans) <- extent(ind)
extent(pop) <- extent(ind)
lu <- resample(lu,ind,method = "bilinear")
trans <- resample(trans,ind,method = "bilinear")
res <- resample(res,ind,method = "bilinear")
pop <- resample(pop,ind,method = "bilinear")
```

```{r}
new <- raster(trans)
new[] <- 1

fun_1 <- function(x,y){ifelse( x == 10 | x == 11 , 2*y, y)} 
fun_2 <- function(x,y){ifelse( x > quantile(trans,0.90) , 3*y, y)}
fun_3 <- function(x,y){ifelse( x > quantile(ind,0.90) , 5*y, y)}
fun_4 <- function(x,y){ifelse( x > quantile(res,0.95) , 7*y, y)}
fun_5 <- function(x,y,z){ifelse( x > quantile(trans,0.90) & y > quantile(pop,0.75), 11*z, z)}
fun_6 <- function(x,y,z){ifelse( x >= 22 & y <= quantile(pop,0.8), 13*z, z)}
fun_7 <- function(x,y){ifelse( x > quantile(res,0.90) , 17*y, y)}
```

```{r}
new <- overlay(lu,new,fun=fun_1)
new[is.na(new[])] <- 1
 
new <- overlay(trans,new,fun=fun_2)
new[is.na(new[])] <- 1

new <- overlay(ind,new,fun=fun_3)
new[is.na(new[])] <- 1
new <- overlay(res,new,fun=fun_4)
new[is.na(new[])] <- 1
new <- overlay(trans,pop,new,fun=fun_5)
new[is.na(new[])] <- 1
new <- overlay(lu,pop,new,fun=fun_6)
new[is.na(new[])] <- 1
new <- overlay(res,new,fun=fun_7)
new[is.na(new[])] <- 1
```

```{r}
crop_extent <- readOGR(#"D:/Selected FUAs/Selected FUAs/Amsterdam.shp")
  "D:/EU/EU GHG Input Data/EU GHG Input Data/FUA Boundaries/G攖eborg.shp")
```

```{r}
crop_extent <- spTransform(crop_extent, CRS(proj4string(new)))

r3 <- mask(new, crop_extent)
r3[is.na(r3[])] <- 1
f <- as.factor(r3)
x <- levels(f)[[1]]
```

```{r}
#set default white
x$color <- rgb(255 ,255 ,255,maxColorValue = 255)

#allocate different colors for each NbS approach
x$color[which(x$ID==2|x$ID==13)] <- rgb(36,139,141,maxColorValue = 255)#Natural Habitat
x$color[which(x$ID==3|x$ID==11|x$ID==33)] <- rgb(12,21,135,maxColorValue = 255)#Road Green
x$color[which(x$ID==5)] <-  rgb(255,165,0,maxColorValue = 255)#GI
x$color[which(x$ID==6|x$ID==39|x$ID==66|x$ID==143|x$ID==429)] <-  rgb(0,112,192,maxColorValue = 255)#Habitat×Road
x$color[which(x$ID==7)] <-  rgb(252,254,191,maxColorValue = 255)#GI×Habitat
x$color[which(x$ID==15|x$ID==165)] <- rgb(209,65,111,maxColorValue = 255)#GI×Road
x$color[which(x$ID==17)] <-  rgb(135,206,235,maxColorValue = 255)#Urban Parks
x$color[which(x$ID==10|x$ID==65)] <-  rgb(252,254,191,maxColorValue = 255)#GI×Habitat
x$color[which(x$ID==30|x$ID==330|x$ID==195|x$ID==2145)] <-  rgb(255,192,203,maxColorValue = 255)#GI×Habitat×Road
x$color[which(x$ID==34|x$ID==221)] <-  rgb(249,231,33,maxColorValue = 255)#Habitat×Parks
x$color[which(x$ID==4641|x$ID==7854|x$ID==17017|x$ID==51051)] <-  rgb(204,204,255,maxColorValue = 255)#Habitat×Road×Parks×Building
x$color[which(x$ID==170)] <-  rgb(204,0,204,maxColorValue = 255)#GI×Habitat×Parks
x$color[which(x$ID==510|x$ID==5610)] <-  rgb(68,12,83,maxColorValue = 255)#GI×Habitat×Road×Parks
x$color[which(x$ID==102|x$ID==2431|x$ID==663|x$ID==1122|x$ID==7293)]<-  rgb(58,82,139,maxColorValue = 255)#Habitat×Road×Parks
x$color[which(x$ID==51|x$ID==187|x$ID==561)] <-  rgb(255,109,182,maxColorValue = 255)#Road×Parks
x$color[which(x$ID==85)] <- rgb(50,182,121,maxColorValue = 255)#GI×Parks
x$color[which(x$ID==119)] <- rgb(195,103,118,maxColorValue = 255)#Parks×Building
x$color[which(x$ID==238|x$ID==1547)] <-  rgb(233,122,88,maxColorValue = 255)#Habitat×Parks×Building
x$color[which(x$ID==255|x$ID==2805)] <-  rgb(78,78,78,maxColorValue = 255)#GI×Road×Parks
x$color[which(x$ID==357|x$ID==1309|x$ID==3927)] <-  rgb(244,187,247,maxColorValue = 255)#Road×Parks×Building
x$color[which(x$ID==595)] <-  rgb(122,38,138,maxColorValue = 255)#GI×Parks×Building
x$color[which(x$ID==7735|x$ID==1190)] <-  rgb(182,109,255,maxColorValue = 255)#GI×Habitat×Parks×Building
x$color[which(x$ID==1785|x$ID==19635)] <-  rgb(156,156,156,maxColorValue = 255)#GI×Road×Parks×Building
x$color[which(x$ID==3570|x$ID==39270)] <-  rgb(204,204,204,maxColorValue = 255)#GI×Habitat×Road×Parks×Building

levels(f) <- x
levels(f)
```

```{r}
tab <- as.data.frame(f, xy = TRUE)
colnames(tab) <- c("long","lat","layer_color")
#library(ggplot2)
p<- ggplot(tab,aes(long, lat, fill = layer_color)) +    
scale_fill_manual(values = c("#FFFFFF"=rgb(255, 255,255, 100, maxColorValue = 255)#set white as transparent 
                             ,"#F9E721"="#F9E721","#FFA500"="#FFA500","#E97A58"="#E97A58",
"#FF6DB6"="#FF6DB6","#87CEEB"="#87CEEB","#7A218A"="#7A218A","#440C53"="#440C53","#CCCCCC"="#CCCCCC",
"#9C9C9C"="#9C9C9C","#4E4E4E"="#4E4E4E","#248B8D"="#248B8D","#32B679"="#32B679","#F4BBF7"="#F4BBF7",
"#3A528B"="#3A528B","#0070C0"="#0070C0","#0C1587"="#0C1587","#FCFEBF"="#FCFEBF","#C36776"="#C36776",
"#FFC0CB"="#FFC0CB","#D1416F"="#D1416F","#CCCCFF"="#CCCCFF","#B66DFF"="#B66DFF","#CC00CC"="#CC00CC"
                             
))+
geom_polygon(data = crop_extent, aes(x = long, y = lat, group = group), colour = "black", fill = NA)+
geom_raster()
```

```{r}
library(ggspatial)
library(patchwork)
library(ggsn)

p1=p +theme_bw()+theme(axis.text.x=element_text(size=15),axis.text.y=element_text(size=15),panel.grid.major = element_blank(),panel.grid.minor = element_blank(),axis.title = element_blank(),plot.title=element_text(hjust=0.5,vjust=-7,size=20))+labs(title = "Gothenburg")+guides(fill="none")+annotation_scale()
p1
```

```{r}
writeRaster(f, "D:/EU/comparison/rasters new/GOT_NEW.tif", options=c('TFW=YES'),overwrite=TRUE)
```
